hunav_loader:
  ros__parameters:
    yaml_base_name: agents_house_trapped_open
    simulator: Gazebo Classic
    map: house
    publish_people: true
    global_goals:
      1:
        x: 0.85
        y: 0.0
      2:
        x: -0.85
        y: 0.0
      3:
        x: 0.0
        y: 0.85
    agents:
      - agent1
      - agent2
      - agent3
    agent1:
      id: 1
      group_id: -1
      skin: 0
      max_vel: 0.05
      radius: 0.4
      goal_radius: 0.1
      cyclic_goals: false
      init_pose:
        x: 0.85
        y: 0.0
        z: 1.250
        h: 3.14159
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 10.0
      goals:
        - 1
    agent2:
      id: 2
      group_id: -1
      skin: 1
      max_vel: 0.05
      radius: 0.4
      goal_radius: 0.1
      cyclic_goals: false
      init_pose:
        x: -0.85
        y: 0.0
        z: 1.250
        h: 0.0
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 10.0
      goals:
        - 2
    agent3:
      id: 3
      group_id: -1
      skin: 2
      max_vel: 0.05
      radius: 0.4
      goal_radius: 0.1
      cyclic_goals: false
      init_pose:
        x: 0.0
        y: 0.85
        z: 1.250
        h: 4.71238
      behavior:
        type: Regular
        configuration: 2
        goal_force_factor: 2.0
        obstacle_force_factor: 10.0
        social_force_factor: 5.0
        other_force_factor: 10.0
      goals:
        - 3
